JETUT-72: rewrote web profile introduction
virtua-tech/jakartaee-tutorial pull request #24
Opened 2023-06-13 13:37 UTC by BalusC

2023-06-13 13:46 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +. These objects are delivered to a web component, which can interact with JavaBeans components or a database to generate dynamic content.
Personally not a fan of wording "JavaBeans components". How is this term used in CDI chapters?

2023-06-13 13:50 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +----
Probably a screenshot of a folder structure in Eclipse IDE is a better idea?

2023-07-06 12:41 UTC, arjantijms commented
Looks good, the term "web component" as part of the archaic "application client component, applet component, web component, ejb component" is maybe debatable, but the spec still defines it and it's used all over the place.

2023-07-06 12:41 UTC, arjantijms approved these changes

2023-07-27 16:00 UTC, kito99 requested changes

2023-07-28 10:16 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +----
Okay :)

2023-07-28 10:17 UTC, BalusC commented
> Looks good, the term "web component" as part of the archaic "application client component, applet component, web component, ejb component" is maybe debatable, but the spec still defines it and it's used all over the place.

I also had my doubts on this term but it's indeed used all over the place including images.

2023-07-28 10:30 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +In the Jakarta EE platform, web applications are represented by web components as seen in xref:jakarta-web-application-request-handling[xrefstyle=short].
I've renamed "JavaBeans components" to "Beans" in the image.

2023-07-28 10:31 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +The response is usually represented as a HTML document along with assets.
The term "assets" is expanded in next chapter. But I think you're right to expand it sooner.

2023-07-28 10:32 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +Development of presentation-oriented web applications is covered in [TBD].
Ah okay!

2023-07-28 10:37 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> -Web components can be Jakarta servlets, web pages implemented with Jakarta Faces technology, web service endpoints, or Jakarta Server Pages.
Hmm you're commenting on a block that's deleted/modified?

2023-07-28 10:41 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +
This is the 'Web Profile' section. REST in stand-alone JAR is supposed to be detailed in 'Core Profile' section.

2023-07-28 10:43 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
Ok, I've added a hyphen before 'based' all over place.

2023-07-28 10:43 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +[source]
Can .. wasn't sure how, will look.

2023-07-28 10:44 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +But it does not implement Jakarta REST, Jakarta CDI, Jakarta Faces nor Jakarta Tags.
Really?

2023-07-28 10:45 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +This will be detailed in the chapter associated with the example project.
webapp004.adoc "Mapping URLs to Web Components", unsure how exactly to link.

2023-07-28 10:45 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +Development of service-oriented web applications is covered in [TBD].
Done but in a modified form (JAX-WS link dropped).

2023-07-28 10:46 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +Development of presentation-oriented web applications is covered in [TBD].
Done, but in a modified form: it was first Faces then Servlet now the other way round.

2023-07-28 10:47 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +The exact location depends on the runtime used:
I wanted to be runtime agnostic. I just gave a few examples of most popular ones to give a general idea. But I'll add a phrase "refer to the documentation for your servlet container" as well.

2023-07-28 10:52 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +The exact location depends on the runtime used:
> Does the example deploy to anything via maven

No. Not yet. I had in mind to add at least 3 profiles which download the server and then start/deploy it but that's going to be a bit of work.

2023-07-28 10:53 UTC, BalusC commented on src/main/asciidoc/webapp/webapp004.adoc
> +As a service-oriented web application, the response is represented as plain text.
Response is not HTML, but point taken, I'll clarify.

2023-07-28 10:56 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +==== Running The Example Projects
Examples have not been updated yet.

2023-07-28 10:59 UTC, BalusC commented
@kito: your comments have been addressed so far possible: https://github.com/virtua-tech/jakartaee-tutorial/pull/24/commits/d40b774ca836138c789bbc0c6dd3aeae6434a5a8

2023-07-28 11:00 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +[source]
Sorry, not really sure how to callout from a folder structure in ASCII art.

2023-07-28 15:09 UTC, kito99 commented on src/main/asciidoc/webapp/webapp001.adoc
> -Web components can be Jakarta servlets, web pages implemented with Jakarta Faces technology, web service endpoints, or Jakarta Server Pages.
doh! you're right.

2023-07-28 15:10 UTC, kito99 commented on src/main/asciidoc/webapp/webapp002.adoc
> +[source]
yeah, me neither...

2023-07-28 15:11 UTC, kito99 commented on src/main/asciidoc/webapp/webapp002.adoc
> +But it does not implement Jakarta REST, Jakarta CDI, Jakarta Faces nor Jakarta Tags.
man, I was not doing a good job reviewing. I don't know what I was thinking.

2023-07-28 15:12 UTC, kito99 commented on src/main/asciidoc/webapp/webapp002.adoc
> +This will be detailed in the chapter associated with the example project.
@jhammen  can you help here?

2023-07-28 15:18 UTC, kito99 commented on src/main/asciidoc/webapp/webapp002.adoc
> +[source]
Let's leave it as-is for now, then.

2023-07-28 15:56 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +==== Running The Example Projects
Just updated the tech/approach. Previous examples were written with mindset of previous decade.

2023-07-28 16:22 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +A service-oriented web application generates dynamic data structures in response to HTTP requests.
And added `(also called a "website")` to the presentation-oriented one.

2023-07-28 16:23 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +Jakarta REST is a RESTful web service framework that can be executed on a servlet container and act as a service-oriented web application.
Yes. Unsure how to improve tho. I've for now remapped subsequent occurrences to 'It'

2023-07-28 16:25 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +A servlet container is a kind of a web container that can be part of a Jakarta runtime such as an application server.
Yes indeed. It was renamed to "servlet container". This sentence is now the definition of "servlet container" itself.

2023-07-28 16:26 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +A deployment descriptor file must comply to the schema described in the associated specification.
I have clarified the sentence.

2023-07-28 17:27 UTC, jhammen commented on src/main/asciidoc/webapp/webapp002.adoc
> +This will be detailed in the chapter associated with the example project.
xref:web:webapp/webapp.adoc#_mapping_urls_to_web_components[Mapping URLs to Web Components]

2023-07-29 20:18 UTC, kito99 requested changes

2023-07-29 20:18 UTC, kito99 commented on src/main/asciidoc/webapp/webapp002.adoc
> +This will be detailed in the chapter associated with the example project.
@BalusC ^

2023-07-29 20:18 UTC, kito99 commented on src/main/asciidoc/webapp/webapp002.adoc
> +==== Running The Example Projects
@BalusC ok, looks like the examples that go with this chapter are finished, right? can you raise a PR for those?

2023-08-02 15:01 UTC, BalusC commented on src/main/asciidoc/webapp/webapp002.adoc
> +==== Running The Example Projects
The examples are only rewritten in the tutorial. They are not rewritten in jakartaee-examples project. I will start today.

2023-08-02 15:02 UTC, BalusC commented on src/main/asciidoc/webapp/webapp001.adoc
> +A servlet container is a kind of a web container that can be part of a Jakarta runtime such as an application server.
Ok point taken. I dropped the "is a kind of a web container that" part.

2023-08-09 00:32 UTC, kito99 approved these changes

2023-08-10 14:25 UTC, merged